import ProjectCard from "./ProjectCard";

const projectsData = [
  {
    id: 1,
    title: "The Story of Jetwing Vil Uyana",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/N4hO4O51nDk?si=6SiYfHLU54s494fp",
    isFeatured: true,
  },
  {
    id: 2,
    title: "Chef Factor - Culinary Excellence",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=3JLmpT5A0oo&t=28s&pp=ygULY2hlZiBmYWN0b3I%3D",
    isFeatured: true,
  },
  {
    id: 3,
    title: "All Ears Elephant Podcast",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=xdBPbPS2A-0&pp=ygUZYWxsIGVhcnMgZWxlcGhhbnQgcG9kY2FzdA%3D%3D",
    isFeatured: true,
  },
  {
    id: 4,
    title: "All Ears Elephant Podcast - Episode 2",
    category: "Video Production",
    date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=MJ9XSk-JqHU&t=1s&pp=ygUZYWxsIGVhcnMgZWxlcGhhbnQgcG9kY2FzdA%3D%3D",
    isFeatured: true,
  },
  {
    id: 5,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=ShEbONmfY_c",
    isFeatured: false,
  },
  {
    id: 6,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=L2HhEs2JmM8&pp=0gcJCRUKAYcqIYzv",
    isFeatured: false,
  },
  {
    id: 7,
    title: "Jetwing Hotels Sustainability",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=YbB5GMy-VUk&pp=ygUdamV0d2luZyBob3RlbHMgc3VzdGFpbmFiaWxpdHk%3D",
    isFeatured: false,
  },
  {
    id: 8,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=3cZRmQL-DH0&t=13s",
    isFeatured: false,
  },
  {
    id: 9,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/P2IdQRA7WmQ?si=YstPMBTPiKX3Qc6-",
    isFeatured: false,
  },
  {
    id: 10,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/qgZ-dVbiIHU",
    isFeatured: false,
  },
  {
    id: 11,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=V3XfcETxGwA",
    isFeatured: false,
  },
  {
    id: 12,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=S6Oi0_xGD-g&pp=0gcJCRUKAYcqIYzv",
    isFeatured: false,
  },
  {
    id: 13,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=nC3Irce3GCE",
    isFeatured: false,
  },
  {
    id: 14,
    title: "Video Project",
    category: "Video Production",
    date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/aTHT-KPCBnA?si=etqfmbk7Z-iS_slA",
    isFeatured: false,
  },
  {
    id: 15,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/EHo5baedp3g",
    isFeatured: false,
  },
  {
    id: 16,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=8gJ7cwuoYkw",
    isFeatured: false,
  },
  {
    id: 17,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=pQzBp2hi2_g",
    isFeatured: false,
  },
  {
    id: 18,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=tE5tZuKXGIo",
    isFeatured: false,
  },
  {
    id: 19,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=QgEnQuL7_nI",
    isFeatured: false,
  },
  {
    id: 20,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=ByXDXPFeruU",
    isFeatured: false,
  },
  {
    id: 21,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=jCr2KArzbuI",
    isFeatured: false,
  },
  {
    id: 22,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=hDF0y3IjKQs",
    isFeatured: false,
  },
  {
    id: 23,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=Mn7I6mDP-2c",
    isFeatured: false,
  },
  {
    id: 24,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=9DXf-pOms8Y",
    isFeatured: false,
  },
  {
    id: 25,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=t0aibHmqmCI",
    isFeatured: false,
  },
  {
    id: 26,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=2JoXZweFK30",
    isFeatured: false,
  },
  {
    id: 27,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=G2wMbsIEFn8",
    isFeatured: false,
  },
  {
    id: 28,
    title: "Video Project",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://www.youtube.com/watch?v=59oVwJvLzzc",
    isFeatured: false,
  },
  {
    id: 29,
    title: "Green Lanka Tea Factory",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/0cFQUL5_WjU",
    isFeatured: false,
  },
  {
    id: 30,
    title: "New Year wish - 2026",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/Sl3-NwLyUzg",
    isFeatured: false,
  },
  {
    id: 31,
    title: "Christmas Wish",
    category: "Video Production",
    // date: "Dec 16 2025",
    imageUrl: "",
    link: "https://youtu.be/Dn97qKn65_I",
    isFeatured: false,
  },
];


const Projects = () => {
  return (
    <div>
      <section className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-8 sm:py-12 md:py-16 mt-20">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8 items-start">
        {projectsData.map(project => (
          <ProjectCard key={project.id} project={project} />
        ))}
      </div>
    </section>
    </div>
  )
}

export default Projects
